### ISSUE TITLE
STREAM_web crashes when trying to display gene on subway plot

### ISSUE THREAD

**Issue by ggersche** [pinellolab/STREAM_web#1] opened 2019-03-24 18:54 UTC
Hi,

Thanks for this nice software. I had tried the website but as it is down, I am now trying to to use the docker image for the web interface. Sadly, it always crashes when I'm trying to display a specific gene (second step) on the subway plot.

Here is the error message I can see on the terminal : 
[2019-03-24 18:36:15,508] ERROR in app: Exception on /compute/_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 556, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 513, in add_context
    output_value = func(*args, **kwargs)
  File "/stream_web/app.py", line 4152, in compute_trajectories
    with open(gene_coords, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/RESULTS_FOLDER/STREAM_ecfb6f6c-16ec-4e21-9f5c-a2d42838a364/S5/subway_coord_Mpz.csv'

It seems to me that there is something wrong with the /tmp/RESULTS_FOLDER.
What do you think ?

Thanks for you help!

**Comment by huidongchen** [comment] 2019-04-10 22:19
Hi,
Thanks for your interest in STREAM website. Sorry about the slow response. It has been quite hectic for a while. I was just able to get back to the issue.

You are right. It was indeed a bug in our code when we were transitioning from python2 to python3. Now it is fixed.

If you do `docker pull pinellolab/stream_web`, it will get updated. Please let me know how it goes.

**Comment by ggersche** [comment] 2019-04-10 23:29
Hi,

Thank your for your reply.

I enthusiastically updated Stream and tried it again.
But now it doesn’t even manage to compute trajectories …

I get this error message : 

[2019-04-10 23:26:53,455] ERROR in app: Exception on /compute/_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 556, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 513, in add_context
    output_value = func(*args, **kwargs)
  File "/stream_web/app.py", line 3342, in num_clicks_compute
    cell_label_df = pd.read_csv(cell_label[0],sep='\t',header=None,index_col=None,compression= 'gzip' if cell_label[0].split('.')[-1]=='gz' else None)
IndexError: list index out of range

Do you know what it means ?

Best regards

Gaspard

**Comment by huidongchen** [comment] 2019-04-10 23:36
I assume the format of your cell label file is not correct.  Please check the input requirement for STREAM pipeline [https://github.com/pinellolab/STREAM#input-file-form](url)

You can also find some example datasets here [https://github.com/pinellolab/STREAM#example](url). Please make sure the files meet the required format before feeding them to STREAM.

**Comment by ggersche** [comment] 2019-04-10 23:45
Ah, thanks.
I thought that a cell label file was optional so I only put a data matrix.
Is it mandatory now ?

Many thanks for your help.

**Comment by huidongchen** [comment] 2019-04-11 00:02
You are right ! It is optional. It is just another bug introduced by the new update.. Sorry about it. I should have tested it more carefully. 

As a stopgap, can you create a label file with the same label and also a corresponding label color file? This should be able to help get around the issue.  I will try to fix it shortly.

**Comment by ggersche** [comment] 2019-04-11 07:33
Hi,

I tried it this morning with a label but it still crashes and I get this on the terminal …

It seems not to be able to access a tmp file, no?

Best regards,

Gaspard


[2019-04-11 07:26:54,755] ERROR in app: Exception on /compute/_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 556, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/opt/conda/lib/python3.7/site-packages/dash/dash.py", line 513, in add_context
    output_value = func(*args, **kwargs)
  File "/stream_web/app.py", line 3378, in num_clicks_compute
    with open(edges, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/RESULTS_FOLDER/STREAM_9e9abb21-05f5-4c65-9a5d-0c3b06326d0e/edges.tsv'

**Comment by huidongchen** [comment] 2019-04-11 14:20
Hi Gaspard,

The bugs should be fixed now if you do `docker pull pinellolab/stream_web`. You don't have to create a label file yourself any more.

Regarding the error message you saw, they are harmless. It's due to Dash continuously looking into a folder during the computation. The moment the folders or files are generated, the error will be gone. 

Please let me know how it goes.

Best,
Huidong

**Comment by ggersche** [comment] 2019-04-11 15:32
Hi Huidong,

I have tried again and still nothing happens.
I also tried on your website and it was the same thing :(

Any idea why ?

If you want I can send you my matrix but I believe it is in the right format as it worked in the past.

Best,

Gaspard

**Comment by huidongchen** [comment] 2019-04-11 17:34
I'm sorry that the issue still persists. I have tested it in several different cases and they all worked. So it's a bit hard for me to debug without reproducing the error you are seeing.

But I would be more than happy to take a look if you could share with me the dataset you are using.

**Comment by lucapinello** [comment] 2019-04-11 17:38
Hi thanks for trying STREAM!

In addition to sending us the dataset, I want to do double check that you
are using the latest version of the docker image.

To do so before running the docker command to launch the website please
execute this command to update your image:

docker pull pinellolab/stream_web

Please let us know if this fixes your problem.

Thanks,

Luca

**Comment by ggersche** [comment] 2019-04-12 12:10
Good afternoon,

I ran a docker pull command and it told me I was up to date.
However, when I tried again this time it worked!
So I must have been doing something wrong yesterday ...

Many thanks for you help!

Gaspard

**Closed as completed** 2019-04-17 23:14 UTC
